#!/usr/bin/env python
# _*_ coding:utf-8 _*_

from __future__ import division
import re
import time
import os
import pymysql
from optparse import OptionParser

# 连接mysql数据库
def conmysql():
    try:
        conn = pymysql.connect(host='122.228.208.143', user='xxx', passwd='xxxx', db='sys_tool',
                               port=5601, charset="utf8")  # 链接数据库
        cursor = conn.cursor(pymysql.cursors.DictCursor)
        return conn, cursor

    except pymysql.Error as e:
        print "Mysql Error %d: %s" % (e.args[0], e.args[1])


con, cur = conmysql()


def getbandwidth(eth='eth0',intevel=1):
    a = open('/proc/net/dev')
    data = a.read()
    patten = eth + '.*'
    conn, cursor = conmysql()
    if not re.search(patten,data):
        print "The ETHname not have"
        exit(1)

    Rev_old = re.search(patten,data).group().replace(':',' ').split()[1]
    Send_old = re.search(patten,data).group().replace(':',' ').split()[9]
    a.close()

    while True:
        data_list = []
        gpus = sys.argv[5]
        time.sleep(int(intevel))
        a = open('/proc/net/dev')
        data = a.read()
        Rev = re.search(patten, data).group().replace(':', ' ').split()[1]
        Send = re.search(patten, data).group().replace(':', ' ').split()[9]
        diff_Rev = int(Rev) - int(Rev_old)
        diff_Sen = int(Send) - int(Send_old)
        diff_M = diff_Rev * 8 / 1024 / 1024/ int(intevel)
        diff_S = diff_Sen * 8 / 1024 / 1024 / int(intevel)
        SNO = gpus
        times = time.strftime("%Y%m%d-%H:%M:%S")
        Recevie = '%6.2f Mbps(byte is %d)' % (diff_M, diff_Rev)
        Sends = '%6.2f Mbps(byte is %d)' % (diff_S, diff_Sen)
        Processes = os.popen('netstat -an | grep tcp |wc -l').readline().strip().split('\n')
        # 这个也可以;
        # sql = "insert into VpsFlowMonitor(Sno,Time,Recevie,Send,Process) values(%s, %s, %s, %s, %s)"%(SNO, times, Recevie, Sends, Processes)
        # cursor.execute(sql)
        lit = (SNO, times, Recevie, Sends, Processes)
        sql = ("insert into VpsFlowMonitor(Sno,Time,Recevie,Send,Process) values(%s, %s, %s, %s, %s)")
        cursor.execute(sql, lit)
        conn.commit()

        Rev_old=Rev
        Send_old=Send
        a.close()


if __name__ == '__main__':
    import sys

    usage = """python xx.py [-i ethname] [-t interveltime]
           Example:python xx.py -i eth0 -t 1"""

    parser = OptionParser(usage=usage,)

    parser.add_option('-i','--interface',dest='interface',default='eth0',help='Wann to interface')
    parser.add_option('-t', '--time', dest='intevel', type='int', default='1', help='The intevel time')
    (options, args) = parser.parse_args()
    print "The interafce is %s and the intevel time is %d" % (options.interface, options.intevel)
    getbandwidth(options.interface, options.intevel)

