#!/usr/bin/env python
# _*_ coding:utf-8 _*_

import smtplib
from email.header import Header
from email.mime.text import MIMEText
import sys
mail_host = 'smtp.126.com'
mail_user = 'xxxx'
mail_pass = 'xxxx'
mail_postfix = '126.com'


def send_mail(to_list,subject,content):
    #me = "xxxxxxx zabbix 监控告警"+"<"+mail_user+"@"+mail_postfix+">"
    me = ("%s<xxxxxx@126.com>")%(Header('xxxxxx zabbix监控告警!','utf-8'),)
    msg = MIMEText(content, 'plain', 'utf-8')
    msg['Subject'] = subject
    msg['From'] = me
    msg['to'] = to_list
    try:
        s = smtplib.SMTP()
        s.connect(mail_host)
        s.login(mail_user,mail_pass)
        s.sendmail(me,to_list,msg.as_string())
        s.close()
        return True
    except Exception,e:
        print str(e)
        return False
if __name__ == "__main__":
    send_mail(sys.argv[1], sys.argv[2], sys.argv[3])
